### ISSUE TITLE
Pixinsight repository is not in sync with github releases

### ISSUE THREAD

**Issue by dts350z** [jarmoruuth/AutoIntegrate#15]
I configured the repository in pixinsight but it is still on 1.41 with no updates available.

https://ruuth.xyz/autointegrate/

**Comment by jarmoruuth** [comment]
Hi, Just to clarify, I assume that you did get v1.41 through the PixInsight update.

Right now the latest version available through the PixInsight update is v1.41. Releases here in GitHub are ahead of those that are available in automatic updates.

I have not set up every GitHub release to the automatic update system. I wanted to avoid too frequent updates and it still needs some manual work. So now there may be three levels of versions: one in automatic updates, one in GitHub release and web page, and a test version in GitHub master branch.

I understand that this looks a bit confusing so I think I will switch to a model where automatic updates, web page and latest GitHub release are in sync. 

I may also fully automate PixInsight updates. I cannot automatically generate list of changes so then that information need to checked from here.

Jarmo
