### ISSUE TITLE
More of a question: How to save state of Dropdowns

### ISSUE THREAD

**Issue by ricandersonva** [jarmoruuth/AutoIntegrate#18]
Jarmo, I would like to save the state of all the drop-down menus (ie, open vs closed) in the save settings button. It would be nice to start with the interface taking up less real estate on the display. 1) what control sets the state? and 2) can it be stored and saved in the "save" button?

**Comment by jarmoruuth** [comment]
Hi Ric, This is a good point, I have been considering it sometimes. I will take a look, it should be relatively easy to add as one of the parameters saved to persistent settings and possibly also to Json file.
Jarmo

**Comment by jarmoruuth** [comment]
I have pushed to the master branch a change that saves collapsible section status.
 
Collapsible section status saved when changed and restored when script starts. This should help with smaller displays where default setup does not fit on the screen. This functionality is available on all screens so section status is always restored  to the last state.

Not sure if this is as good as a separate save option where you could set a default startup setup. Let's see if that needs to be done also.

**Comment by ricandersonva** [comment]
Thanks I will give it a try

**Comment by jarmoruuth** [comment]
Fixed in 1.45
