### ISSUE TITLE
AutoIntegrate windows sizing issue

### ISSUE THREAD

**Issue by tlkw79** [jarmoruuth/AutoIntegrate#21]
Hi,

I can't resize the AutoIntegrate windows so the bottom part disappears. Please take note.

Thanks.

**Comment by jarmoruuth** [comment]
Hi, If your problem is a small screen size then you need to close some sections to make the dialog smaller. Then you should be able to resize it and see the bottom part. The script will remember the open/close status of sections so the next time you should not have the problem. In the next release I need to make the startup window smaller.

But you still cannot make the dialog window smaller than the size of the open sections. I need to check if something can be done for it.

Jarmo

**Comment by tlkw79** [comment]
The same thing happened in my Notebook. Cannot resize the dialog windows.

**Comment by jarmoruuth** [comment]
Can you give any more details, like an image how it looks?

**Comment by tlkw79** [comment]
![2022-04-22_071607](https://user-images.githubusercontent.com/28095685/164566388-99791c48-fd16-4654-a93a-6c7c16e7c20a.jpg)

**Comment by jarmoruuth** [comment]
Thanks for the info! This is the problem I mentioned earlier.  You need to close/minimize some sections to make the dialog smaller. In this case if you minimize "Other parameters" and "Extra processing" sections you should be able to see the whole dialog and also resize it.

The script will remember the open/close status of sections so the next time you should not have the problem. In the next release I need to make the startup window smaller.

**Comment by naixx** [comment]
Aactually minimizing doesn't help
![image](https://user-images.githubusercontent.com/1759282/197309006-ce44dc06-3555-4cfa-8706-d7b5dafad1d7.png)

**Comment by jarmoruuth** [comment]
Would it help if you go to Interface settings, change Preview width and height, click Save and restart the script? Or if you do not want preview you can disable it there too.

**Comment by naixx** [comment]
Yes, it helps. Previously if I try to resize window from top, the script crashes and disappears from scripts menu.

**Comment by jarmoruuth** [comment]
Good to hear that it helps. But really strange that it crashed and disappeared on resize.

**Comment by jarmoruuth** [comment]
Old versions may have too large preview size, manually setting a smaller size in Interface settings should help. Now there is also a button to reset interface in case it not automatically adjusted.
