### ISSUE TITLE
No Issue here, just discussion of the inserting of Canon Linear fix script

### ISSUE THREAD

**Issue by ricandersonva** [jarmoruuth/AutoIntegrate#23]
So, I haven't leapt into trying to code the insert of the Canon linear fix script. I would love to see how you would do it if you get the inclination.   Here is my work-flow on how I'm processing with the current script. (Oh, and this applies to 1.5.1 because I havent started with 1.5.2)

	1. Step 1 calibrate and debayer in 
		a. In |Other parameters| check |debayer only|
		b. Save to normal folders
	2. With an image container load debayered files from 1.
		a. Send them through canon lin fix
	3. Run Script and with the fixed debayered files with |debayer| set to "None" and no calibration files loaded, with whatever preferences needed, run again to finish the processing.

If you do this I would love to see any notes on what you did to insert the needed coding.  Thanks for considering.
Ric Anderson

**Comment by jarmoruuth** [comment]
CanonBandingReduction.js is a nicely written script and there is a separate BandingEngine that was easy to embed. I did a very quick test and it did not crash when it was embedded into AutoIntegrate. 

I have attached a version of AutoIntegrate.js that always runs BandingEngine. So there are no option for it yet. It would be nice to know if it works for your files. Need to figure out the licensing later. It is free software but with a GNU license.

[AutoIntegrateBanding.zip](https://github.com/jarmoruuth/AutoIntegrate/files/9728367/AutoIntegrateBanding.zip)

**Comment by ricandersonva** [comment]
I am looking at the 1.52 and 1.53 test scripts together and see the parameters there from the CBR script. I do adjust those for my equipment, so I will tweak them in the 1.53 script to see if I can get results I need.

Ric

 

From: Ric Anderson ***@***.***> 
Sent: Saturday, October 8, 2022 9:31 AM
To: 'jarmoruuth/AutoIntegrate' ***@***.***>; 'jarmoruuth/AutoIntegrate' ***@***.***>
Cc: 'Author' ***@***.***>
Subject: RE: [jarmoruuth/AutoIntegrate] No Issue here, just discussion of the inserting of Canon Linear fix script (Issue #23)

 

 

Jarmo, 

Script ran with no errors, yes. However, the results are a little different than usually see. I did all 6 of the large panels in the current matrix I’m working on and am seeing a difference in each image where there is brighter nebula data on the image, the horizontal areas (rows) that do not have that brightness are considerably darker than the other darker parts of the image.  So, I would say that that it certainly did run the banding engine, but it’s perhaps too blunt an instrument without some tweaking which maybe the CanonBandingReduction script provides. So, probably not a good idea to implement the engine without some control parameters. 

 

I think after debayer is the right place to run it in the process flow because it would expect 

 

Attached is an example.

Ric

**Comment by jarmoruuth** [comment]
Thanks for testing. I actually have some Canon data so did a bit more testing and the result is not good. I will take a closer look and see what options would be needed.

Jarmo

**Comment by ricandersonva** [comment]
I usually set highlightprotect to true. I just tested that and it looks pretty good. Also, I did a run splitting data into narrowband (actual rgb is through L-enhance filter) and processed with Dynamic HOO and that looks good also. 

So, It might be fine to leave hilightprotect as true. Certainly saves me lots of manual effort. I do love your script.

Ric

**Comment by jarmoruuth** [comment]
My results were not very good banding removal enabled. But there was no real banding in those files. I guess some kind of configuration is needed. I am in the process to split my one big file into a few smaller ones. If I ever get that completed I try to include the banding reduction to the script.

Jarmo

**Comment by ricandersonva** [comment]
I have used it a few images with highlight protect checked and have seen some good results. It probably needs an on/off switch because it's not always needed. I am also trying various dither sizes to eliminate the problem at exposure time.

**Comment by jarmoruuth** [comment]
Ok, sounds good. I will add some options once I get code reorganization done. By default it will be off.

Jarmo

**Comment by jarmoruuth** [comment]
I have a new version available that has the code split into multiple files and it includes the banding reduction. There is configuration available in section Banding, binning and cosmetic correction settings. I have attached a zip file with latest source from code-reorg branch if you want to try it.

[AutoIntegrate-code-reorg.zip](https://github.com/jarmoruuth/AutoIntegrate/files/9789767/AutoIntegrate-code-reorg.zip)

**Comment by jarmoruuth** [comment]
Banding reduction is included in v1.54.
