### ISSUE TITLE
Not an Issue - Thanks for adding the banding

### ISSUE THREAD

**Issue by ricandersonva** [jarmoruuth/AutoIntegrate#25]
I am testing the Banding with 3.5 hours of narrowband data taken with a modified Canon DSLR.  I will do a with and without to see how it works. I usually use .85 in settings to tone it down.

Thanks, 
Ric

**Comment by jarmoruuth** [comment]
Hi Ric, Great if you can test it. My test set is not good for testing the banding. Please let me know how it works, and if some changes would be needed.
Regards,
Jarmo
