### ISSUE TITLE
Autointegrate pixinsight code update

### ISSUE THREAD

**Issue by ricandersonva** [jarmoruuth/AutoIntegrate#27]
Hi Jarmo, Hope you are doing well.

I had not been using the pixinsight update process that you are supporting for autointegrate until this morning. I was using version 1-54 and installed it by downloading it to my custom pixinsight download folder and then running it under scripts | execute scripts.

I just added your code update url (https://ruuth.xyz/autointegrate) to pixinsight and was able to automatically update the code using pix update facilities. That worked fine and I then found autointegrate under Scripts | Batch Processing. 

When I run it, I get this error:

run --execute-mode=auto "C:/Program Files/PixInsight/src/scripts/AutoIntegrate/AutoIntegrate.js"

Processing script file: C:/Program Files/PixInsight/src/scripts/AutoIntegrate/AutoIntegrate.js
*** Error: *** Error: C:/Program Files/PixInsight/include/pjsr/NumericControl.jsh, line 391: unmatched #endif preprocessor directive.

Any insights?

**Comment by ricandersonva** [comment]
Also, I tried to download as usual and went to the unzipped folder and ran it under execute scripts. I got these additional errors:

run --execute-mode=auto "G:/PixinsightDownload/AutoIntegrate-1.56.1/AutoIntegrate-1.56.1/AutoIntegrate.js"

Processing script file: G:/PixinsightDownload/AutoIntegrate-1.56.1/AutoIntegrate-1.56.1/AutoIntegrate.js
*** Error: *** Error: G:/PixinsightDownload/AutoIntegrate-1.56.1/AutoIntegrate-1.56.1/AutoIntegrateEngine.js, line 94: include file not found: ../AdP/CommonUIControls.js

**Comment by jarmoruuth** [comment]
Are you running the latest PixInsight version? An old PixInsight version could be one reason.

For the error "include file not found: ../AdP/CommonUIControls.js":

Starting from AutoIntegrate version 1.56 there is a dependency to ImageSolver script
in PixInsight distribution. This means that ImageSolver files must be in the ../AdP
directory relative to AutoIntegrate directory. If you have manually downloaded 
AutoIntegrate from GutHub you need to create ../AdP directory and copy the contents 
of Pixinsight-install-directory/src/scripts/AdP there. In Windows the default 
installation path to AdP is C:\Program Files\PixInsight\src\scripts\AdP.

**Comment by ricandersonva** [comment]
Yes, the latest update code. I have also reset pixinsight's settings to the default, thinking that some pointer to path had gotten changed. I am getting the same results using the "pixinsight installed" script. Kind of strange. 

I did copy the adp folder to the downloaded location for the manual script execute, but am not sure which absolute folder it should go into.

my copy of the 1.54 script is still working fine.

**Comment by ricandersonva** [comment]
No. I just realized that I have version 1.8.8-9 and the latest on the distribution site is 1.8.9-1 so evidently i need to download to upgrade. am doing now....

**Comment by ricandersonva** [comment]
That was it! Thanks for you help.
