### ISSUE TITLE
ABE degree configuration

### ISSUE THREAD

**Issue by spodzone** [jarmoruuth/AutoIntegrate#28]
Hi,
I'm comparatively new to AutoIntegrate. Sometimes we have data that would benefit from ABE, but the process has a high default degree of 4 which causes horrendous halo/anti-halo rings around targets occupying large proportions of the centre of the frame - worse than residual gradients it's supposed to be solving. 
There are several places in AutoIntegrate where ABE can be enabled - but I don't see anywhere where the degree could be constrained. 
Would be very grateful if you could add such a configuration option. Thanks.

**Comment by Endolf** [comment]
That would be really useful, I have the same issue when using ABE in autointegrate

**Comment by jarmoruuth** [comment]
Hi,

I must admit I have taken ABE always as is, sometimes it works and sometimes it does not. I have not even looked into configuration of ABE. Thanks for the tip, I will add configuration for degree which I believe is Function degree in ABE tool. Timing for this is also good as I am going to put out a new release soon.

Jarmo

**Comment by jarmoruuth** [comment]
I now have a test version available here in GitHub and in my test repository https://ruuth.xyz/test/autointegrate.

ABE function degree can be configured in _Linear fit, LRGB combination and ABE settings_ section.

Jarmo

**Comment by spodzone** [comment]
Many thanks! Used your test repository. Can confirm it makes a difference. Thanks again especially for the speedy response :)
