### ISSUE TITLE
Pixelinsight gives error code 404 when using repository URL

### ISSUE THREAD

**Issue by KuhlmanBret** [jarmoruuth/AutoIntegrate#30]
Hi,
Thanks for this great script!  I was trying to add the URL:  https://ruuth.xyz/autointegrate

to the repository in PI and I get the error code 404.
It works when I run the script manually.
Thanks for your help,
Bret

**Comment by jarmoruuth** [comment]
Hi Bret, I did a quick test and it works for me. So unfortunately at the moment I have no idea why it does not work. What version of PixInsight you are using?
Jarmo

**Comment by KuhlmanBret** [comment]
Thanks for the quick response!See images:Sent from my iPhoneOn Sep 12, 2023, at 12:35 PM, Jarmo Ruuth ***@***.***> wrote:﻿
Hi Bret, I did a quick test and it works for me. So unfortunately at the moment I have no idea why it does not work. What version of PixInsight you are using?
Jarmo

**Comment by jarmoruuth** [comment]
Hi Bret, Did you post some images? Unfortunately they did not go through, I am not sure if this forum supports images. -- Jarmo

**Comment by KuhlmanBret** [comment]
Oh sorry,
Pix Insight ver 1.8 paid version
added:  https://ruuth.xyz/autointegrate  to the manage update repositories
Get error:  Network error Response code: 404

Thanks for your help,
Bret

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jarmoruuth** [comment]
Have you tried upgrading to the latest PixInsight version 1.8.9-2?

Jarmo

**Comment by KuhlmanBret** [comment]
Hi Jarmo,Got it working.  Turns out I needed to add a “/“ to the end of the URL when adding to repository.  Thanks for all the help.  I really appreciate the script, as a newbie, it has accelerated my learning in PixInsight, while allowing me to process some great images.You might consider adding the / to the end of your link so that dummies like me who just copy and paste don’t have the same issue.Keep up the great work,BretSent from my iPhoneOn Sep 13, 2023, at 5:31 AM, Jarmo Ruuth ***@***.***> wrote:﻿
Have you tried upgrading to the latest PixInsight version 1.8.9-2?
Jarmo

**Comment by jarmoruuth** [comment]
Hi Bret, Great that you got it working! And thanks for letting me know of the solution. I actually did try without the slash "/" at the end but it did not give me an error. But my version was already up to date so maybe that was the reason. I am on Windows. Anyway, I have updated repository links to include the slash "/" at the end.

Regards, 
Jarmo
