### ISSUE TITLE
Removing Stars Multiple Mappings

### ISSUE THREAD

**Issue by danieldh206** [jarmoruuth/AutoIntegrate#34]
You might already know this one
If I try to use star removal "Remove stars before stretch" I keep getting this error. 
[AutoSetup.json](https://github.com/jarmoruuth/AutoIntegrate/files/13653024/AutoSetup.json)

EtaE_AutoRGB_extra
Error: Could not find starless image for star image EtaE_AutoRGB_extra
Processing stopped!

I believe this is because "extra" tasks is not being done on  EtaE_AutoRGB_stars 

If I rename EtaE_AutoRGB_stars to EtaE_AutoRGB_extra_stars the stars are automatically added. 

The auto processes is stopped and only the AutoRGB color pallet is completed. 

Unchecking "Remove stars before stretch" all color mapping complete
AutoIntegrate: Narrowband palette batch completed
[AutoContinue.log](https://github.com/jarmoruuth/AutoIntegrate/files/13652809/AutoContinue.log)

I program in Python and don't know Java well, but looked through AutoIntegrateGUI.js and maybe the easiest temporary fix is to gray out or uncheck "Remove Star" if multiple color pallets are selected. 

Not really an "issue" but I also noticed GradX was rerunning for each color pallet.  Maybe the color mapping loop could be from the "PixelMath:combine RGB". (`function runPixelMathRGBMapping`)

Is there a way to run autointegrate in command line and using jdb debugging or other way to debug like I can do with IPDB in Python?

Daniel

**Comment by jarmoruuth** [comment]
Hi Daniel,

Thanks for finding and reporting these problems! And sorry that there are problems.

I must admit I have not tested these different start remove options like "Remove stars before stretch" for some time. I do not use them myself but I really need to update my automatic test setup.

Graying remove stars options with multiple palettes sound like a good idea, and should be easy to do.

I need to check the GraX if there is a way to avoid multiple runs. Unfortunately this multiple palette thing is very simplistic. Anyway a good idea to check if the mapping loop could be placed to somewhere else.

Script is built deep into PixInsight. So at least I do not any other way to debug it but to generate log files and/or console output.

Jarmo

**Comment by jarmoruuth** [comment]
I quickly tested multiple mappings with "Remove stars before stretch" and it did work for me. Then I checked your json file and noticed that you have set the Extra option to combine starless and star images. Unfortunately you cannot use extra combine in automatic mode if you have not removed the stars also with extra option. Maybe that could be the reason for the error?

Jarmo

**Comment by jarmoruuth** [comment]
Now there is a new error check at startup: Extra combine stars cannot be used during processing if extra remove stars is not set.
This version is still only in GitHub.

**Comment by jarmoruuth** [comment]
Stars are automatically added back after the basic processing. Starless and star images are saved to disk. In the stretching settings you can specify how stars are stretched and combined back.

Jarmo

**Comment by jarmoruuth** [comment]
Fix for this is now available in my PixInsight test repository:  https://ruuth.xyz/test/autointegrate/

**Comment by jarmoruuth** [comment]
Fixed in v1.65.2
