### ISSUE TITLE
 Light Vortex Astronomy

### ISSUE THREAD

**Issue by danieldh206** [jarmoruuth/AutoIntegrate#35]
Light Vortex Astronomy is gone unless the internet archive link is used. The link needs to be removed or updated on the website.
Daniel

**Comment by jarmoruuth** [comment]
Thanks for the note, I removed the links and added a note that the site is no longer available.

You can still find it from wayback site: https://web.archive.org/web/20231214191308/https://www.lightvortexastronomy.com/about-e-eye.html

Jarmo
