### ISSUE TITLE
Problems with Autoinegtrate use with PI v. 1.8.9-2

### ISSUE THREAD

**Issue by mwlsdmwlsd** [jarmoruuth/AutoIntegrate#36]
When I install the script in the latest PI version, I cannot resize the script window to access the buttons at the bottom of the window.  In addition, the Interface Settings tab is missing.  Hence the recommended fix involving changing the preview windows size is not available.

If I try to drag the window downwards or resize the window from one of the corners, the window disappears and crashes PI.

Everything works perfectly with the previous version of PI.

**Comment by jarmoruuth** [comment]
Hi, Sorry to hear that you have problem. Unfortunately script window size is one of the most common problems.

I am on windows and AutoIntegrate v1.68 with PixInsight v1.8.9-2 build 1605 works fine. So for now I cannot reproduce the problem.

There should not have had any recent changes in script window size. The last bigger AutoIntegrate interface change was in v1.64.

When starting the script the output on the Process Console that may give hints what is the problem. Posting that information may help tracking the issue.

You can also try starting the script from the Process Console with the following command line:

run -a="do_not_read_settings" --execute-mode=auto "<path-to-pixinsight>/PixInsight/src/scripts/AutoIntegrate/AutoIntegrate.js"

In Windows <path-to-pixinsight> is C:\Program Files\PixInsight.

It is a bit complicated way but then no AutoIntegrate settings are read from the system and maybe the default setup would work better. And hopefully you should be able to adjust the interface size.

If you add an option -a="do_not_write_settings" to the command line you can test it without writing any AutoIntegrate settings at exit.

If you do not have Interface tab at all that of course points to some bigger problems than a simple window size issue. But hard to know for sure.

Jarmo

**Comment by mwlsdmwlsd** [comment]
Jarmo,
Many thanks for such a prompt reply. Here are the various diagnostic screen grabs that may help in finding a solution to this problem.
First, the error message that results when I run your suggested start up command.  Note that the autointegrate.js file is confirmed as being in the expected file location.

![js file path confirmation](https://github.com/jarmoruuth/AutoIntegrate/assets/69723700/81752722-bd11-4c18-a4ae-a1563762f4ef)
![AI script window after default start up](https://github.com/jarmoruuth/AutoIntegrate/assets/69723700/4856a25b-74d0-4ac5-a80b-f2f90549decd)
![Process console message following default start up](https://github.com/jarmoruuth/AutoIntegrate/assets/69723700/5c48df1f-d4ae-4bd4-9379-ed3153ae08bf)
![Process Console message with suggested script launch command line](https://github.com/jarmoruuth/AutoIntegrate/assets/69723700/b1491c61-51a8-4858-b473-a50400612a9c)

The other screen grabs show the messages reported and the resulting AI screen with the missing tabs.

Many thanks for your help with this.

**Comment by mwlsdmwlsd** [comment]
Jarmo,

 

Many thanks for such a prompt reply. Here are the various diagnostic screen grabs that may help in finding a solution to this problem.

First, the error message that results when I run your suggested start up command.  Note that the autointegrate.js file is confirmed as being in the expected file location.

 

The other screen grabs show the messages reported and the resulting AI screen with the missing tabs.

 

Many thanks for your help with this.

 

GT.

**Comment by jarmoruuth** [comment]
Hi,

You have Singe column interface setting enabled so all settings are under a single "Settings" tab.  If you open Settings tab and close all sections then at the the very end you should be able to find "Interface settings" tab. When you have multiple sections open the Interface section gets pushed below the visible screen area. The same happens with the bottom row buttons. For that reason some of the bottom row buttons are duplicated at the top. Once you find the Interface settings section you can disable Single column if you like.

Please let me know if you still cannot find the Interface section in the Settings tab. There are quite a few sections now so in theory it is possible that you still cannot see it.

For running the AutoIntegrate manually with option run -a="do_not_read_settings" , the error message says that file was not found. Maybe it should "c:/Program Files" instead of "c:/WIndows"?

Jarmo

**Comment by mwlsdmwlsd** [comment]
Jarmo,

 

Some progress following your last suggestion – many thanks for that:

 

Running the bespoke startup script solves some of the problems:

1:  The Interface tab is now visible,

2:  The files table is all visible along with the bottom buttons, but the height is too small.

 

BUT the default script is still not working.

 

Two questions, if you don’t mind:

 

1:  How can the bespoke start-up script be loaded automatically, rather than having to be entered manually?

2:  How can the default AI screen size be changed from 2560x1040, which seems to be the main problem?

 

 

Many thanks,

 

 

GT.

**Comment by jarmoruuth** [comment]
Hi,

Would it work better if you just remove the Single column option in the Interface section? And maybe adjust the preview size to very small at first to ensure that all fits to the screen?

Jarmo

**Comment by mwlsdmwlsd** [comment]
Jarmo,

 

Unfortunately, neither of those suggestions makes any difference.   The bottom of the window is still invisible.

 

Surely somewhere the launch command is stored and can be manually altered.  Similarly somewhere the window size must be defined and can be reduced?

 

 

Many thanks,

 

 

GT.
