### ISSUE TITLE
Error at start of debayering with 19 pictures

### ISSUE THREAD

**Issue by clivemeister** [jarmoruuth/AutoIntegrate#6]
Working with 19 photos in DNG (Adobe Digital Negative) raw format.  They are RGGB Bayer encoded colour images.  Process stops after Cosmetic Correction stage with "Error: Debayer.maxFileReadThreads(): numeric value out of range: 0"

Here is the tail of the log file:
<quote>
[2021-09-12 16:52:27] ===== CosmeticCorrection: 19 succeeded, 0 skipped, 0 canceled =====
[2021-09-12 16:52:27] 02:36.75
[2021-09-12 16:52:27] generateNewFileNames, old D:/Pictures/Astro/2021-09-12 Milky way/DSC00563.dng
[2021-09-12 16:52:27] generateNewFileNames, new D:/Pictures/Astro/2021-09-12 Milky way/AutoOutput/DSC00563_cc.xisf
[2021-09-12 16:52:27] runCosmeticCorrection output[0] D:/Pictures/Astro/2021-09-12 Milky way/AutoOutput/DSC00563_cc.xisf
[2021-09-12 16:52:27] AutoIntegrate: debayerImages, fileNames[0] D:/Pictures/Astro/2021-09-12 Milky way/AutoOutput/DSC00563_cc.xisf
[2021-09-12 16:52:27] Error: Debayer.maxFileReadThreads(): numeric value out of range: 0
[2021-09-12 16:52:27] Processing stopped!
[2021-09-12 16:52:27] Write processing steps to D:/Pictures/Astro/2021-09-12 Milky way/AutoProcessed/AutoIntegrate.log
======================================
Dialog files:
D:/Pictures/Astro/2021-09-12 Milky way/DSC00563.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00564.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00565.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00566.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00567.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00568.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00569.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00570.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00571.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00572.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00573.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00574.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00575.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00576.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00577.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00578.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00579.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00580.dng
D:/Pictures/Astro/2021-09-12 Milky way/DSC00581.dng

Processing options:
Background neutralization true
Start processing...
CreateChannelImages
No preprocessed images found
calibrateEngine, no bias, flat or dark files
run CosmeticCorrection, output *_cc.xisf, no line defects to fix
debayerImages, fileNames[0] D:/Pictures/Astro/2021-09-12 Milky way/AutoOutput/DSC00563_cc.xisf
</quote>

**Comment by jarmoruuth** [comment]
I believe dng files are not debayered. It looks like you did not choose RGGB in the Debayer selection of AutoIntegrate. Could you try with the latest AutoIntegrate version and choose RGGB for debayer? If that does not help it would be useful to get the full log file.

Jarmo

**Comment by clivemeister** [comment]
Hi - I tried both DNG files and the original ARW files from my Sony camera,
and both had the same problem.

Attached is the log file (with the DNG files), with debayer set to RGGB -
before I had it at "auto".  The problem reproduced with just 4 input files,
which keeps the log file down a bit, so I've done that here.

Let me know what else I can do to help.  I tried (extremely naively) just
setting maxFileReadThreads to 1 instead of 0 in the debayer function, but
that didn't help.  I couldn't see any useful docs from PixInsight
explaining what the permissible parameter ranges were here, so I didn't
know what else to try.  I'm on PI 1.8.8-6 Ripley, running on Windows 10, if
that's relevant.

cheers,
Clive

**Comment by jarmoruuth** [comment]
Hi Clive, I cannot find the log file, no idea where the attachment would go here in GitHub. It was not in the email either.  If you like you can send the attachment directly to me at jarmo.ruuth@gmail.com. I can also try with dng file myself, although I have a Fuji camera. And if you like you can send me one of your files. I do not do much debayering myself. I have the latest PI 1.8.8-9. It is getting late in my time zone but I will check tomorrow.

Jarmo

**Comment by jarmoruuth** [comment]
Hi Clive, I tested with some Canon RAW files converted to DNG and those worked fine.  I was using Auto Debayer option as PixInsight recognizes Canon DSLR files. My environment was PixInsight 1.8.8-9, AutoIntegrate 1.02 and Windows 10.

Jarmo

**Comment by clivemeister** [comment]
Hi - well now I just feel daft, as upon downloading the latest PixInsight
1.8.8-9 I find that it all works perfectly :-)    Sorry, I should have
tried this earlier - it's been too long since I was on the receiving end of
bug reports, and I really should have done a bit more legwork before
bothering you!

So I'm happy to report it now works fine.   I ran all 19 of the subs that I
had captured, and after some deal of whirring and a cup of tea, it
completed successfully.  I have to say this is a really impressive piece of
scripting that you've done - nice work indeed, and I'll be starting with
this for my future runs, I'm sure.

As a small compensation for the bother I've put you to, here's a jpeg of
the result - galactic core over North Yorkshire, England, total exposure
time 9m30s, captured on a Sony Alpha 7riii.
[image: AutoRGB.jpg]

cheers
Clive

**Comment by jarmoruuth** [comment]
Hi, Good to hear that it works now. And a great image!

Looks like PixInsight process parameters can create incompatibility between versions. Need to check if there is some way to prevent or detect that.

Jarmo
